name: Deploy and Notify via Telegram
on:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
  pull_request:
    branches:
      - master
    types: [closed]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Wait for Cloudflare Pages Deployment
        id: cf-pages
        uses: WalshyDev/cf-pages-await@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          project: ${{ secrets.CF_PROJECT_NAME }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Telegram Notification
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Cloudflare Pages Deployment Status
            Project: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
            Environment: ${{ steps.cf-pages.outputs.environment }}
            Deployment ID: ${{ steps.cf-pages.outputs.id }}
            URL: ${{ steps.cf-pages.outputs.url }}
            Alias URL: ${{ steps.cf-pages.outputs.alias }}
            Status: ${{ steps.cf-pages.outputs.status }}